### PR TITLE
Customizable server messages

### PR DESCRIPTION
**Pull request by Galapagon**
Changes three areas to allow for users to customize the message the server sends when

- The Server Starts

- Someone Joins the game

- Someone Leaves the game

Also changes these messages to be more visually different from the messages sent when players are talking

### CODE REVIEW

**Comment by maxsupermanhd** [comment]
Oh man im sorry to say that but we are now in work on legacy and detaled mode when all events to discoed delivered by internal server-only mod due to new anti-pirate restrictions. There will be not only customizable messages, mutch more up to custom events printing.

**Comment by maxsupermanhd** [comment]
Also will be cool if this messages was able to change on the go from bot commands

**Comment by Galapagon** [comment]
That sounds so much better than this layered wrapper option, and simpler for more users to handle.
Still I had fun figuring out these changes for myself and thought they might be useful to someone else. I look forward to hearing more about your internal mod!

**Comment by IIPoliII** [comment]
Prefix is corrected as well

**Comment by IIPoliII** [comment]
Accepted - pulling and closing

**Pull request merged**
